### ISSUE TITLE
Sliding expiration is limited to 3 minutes and 34 seconds

### ISSUE THREAD

**Issue by GerardSmit** [mgravell/FASTERCache#12]
When trying to add FASTERCache to an ASP.NET Core application with Sessions, I ran into the following exception:

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.OverflowException: Arithmetic operation resulted in an overflow.
         at FASTERCache.DistributedCache.GetExpiryTicks(DistributedCacheEntryOptions options, Int32& sliding) in /_/src/FASTERCache/DistributedCache.cs:line 307
         at FASTERCache.DistributedCache.WriteValue(ReadOnlySequence`1 value, Byte[]& lease, DistributedCacheEntryOptions options) in /_/src/FASTERCache/DistributedCache.cs:line 64
         at FASTERCache.DistributedCache.WriteAsync(String key, ReadOnlySequence`1 value, DistributedCacheEntryOptions options, CancellationToken token) in /_/src/FASTERCache/DistributedCache.cs:line 373
         at Microsoft.AspNetCore.Session.DistributedSession.CommitAsync(CancellationToken cancellationToken)
```

This is because code the SlidingExpiration is converted to ticks and then to an integer:

https://github.com/mgravell/FASTERCache/blob/6f8f2a1e25b819b7cdc8af78a8c2b748780638b0/src/FASTERCache/DistributedCache.cs#L441

Because of this, the max value of SlidingExpiration is `00:03:34`.  
For my issue, changing the max session to IdleTimeout to 3 minutes fixes this problem:

```cs
builder.Services.AddSession(options =>
{
    options.IdleTimeout = TimeSpan.FromMinutes(3);
});
```

However, 3 minutes is quite small for an idle timeout causing FASTERCache being unusable in this case.

**Comment by mgravell** [comment]
Yep, that's clearly very wrong. For emphasis: this code is very experimental right now - you're very brave! But yes, this needs fixing. If we used millis, I guess that gives us 23 days (46 days if we lose the sign). I think beyond that, for *sliding* expiration, we should just max it - thoughts?

**Comment by GerardSmit** [comment]
> For emphasis: this code is very experimental right now

I figured as much, but I was still curious if it would work 😄

> I guess that gives us 23 days (46 days if we lose the sign). I think beyond that, for sliding expiration, we should just max it - thoughts?

For my use case 23 and 46 days is a long time, since it would store _all_ the sessions of users that visit the ASP.NET Core website during that period. The default value of ASP.NET Core (and IIS) is 20 minutes. So, for me that's completely fine.

---

Just thinking out loud, you could also say that:

```
0 - 100               = milliseconds
100 - uint.MaxValue   = multiply by 10 milliseconds
```

Then the max value would be 497 days. Explained in code:

```cs
TimeSpan ToTimeSpan(uint value)
{
     return TimeSpan.FromMilliseconds(value <= 100 ? value : (long)value * 10);
}


uint FromTimeSpan(TimeSpan value)
{
    const long maxValue = (long)uint.MaxValue * 10;
    
    var ms = value.TotalMilliseconds;
    
    return ms switch {
        <= 100 => (uint)ms,
        <= maxValue => (uint)Math.Round(ms / 10),
        _ => throw new ArgumentOutOfRangeException(nameof(value), $"Sliding expiration can max be {TimeSpan.FromMilliseconds(maxValue)}")
    };
}
```

Between 0ms - 100ms you have full accuracy, while above 100ms the accuracy is 10ms. The higher the value the less likely you'll need milliseconds precision.

**Comment by mgravell** [comment]
The logic makes sense; agree on precision only being important relative to
the scale.
